### ISSUE TITLE
token

### ISSUE THREAD

**Issue by lsamamig** [AgP42/MMM-Netatmo-Presence#1]
Sorry for my silly question but how do you get the token?
I have the client id and the client secret but the body field on the weebhook is empty :(
thanks in advance

**Comment by AgP42** [comment]
Hi, 

you don't need the token, it is generated automatically by the module.

Please read the [README file here](https://github.com/AgP42/MMM-Netatmo-Presence#get-api-connection-params)

The params needed are :
```
//see README.md for details how to get thoses infos						
client_id: 'your add id', 
client_secret: 'your app secret', 
username: 'your Netatmo username (e-mail)',
password: 'your Netatmo password', //communication is https !
home_id: 'your home id', //necessaire pour l'API
```
